# Generated by Django 4.2.17 on 2025-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_newslettersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_purchase_discount',
            field=models.BooleanField(default=True),
        ),
    ]
